made the CF stuff into its own class
chocolate-edition/Chocobot pull request #19
Opened 2024-09-13 00:36 UTC by GildedToxin

2024-09-13 02:54 UTC, Jonah-Hansen requested changes

2024-09-13 02:54 UTC, Jonah-Hansen commented on src/chocobot/curseforge/Curseforge.py
> +     def __init__(self):
Don't need a constructor unless you're actually initializing data from it

2024-09-13 02:54 UTC, Jonah-Hansen commented on src/chocobot/curseforge/Curseforge.py
> +     def update_cf(self) -> None:
Instead of an update method, we can use properties for the dynamic data, so that each time the value is accessed, it does a request. We may need to use async/await when dealing with the requests though or otherwise wait for the request to complete before using the result

Also not necessary for now, but we should be handling errors if the request fails and such. 

You can define an interface for what you expect the data structure to look like, and cast the request result to the interface allowing you to more easily access certain fields from it

2024-09-13 03:09 UTC, GildedToxin commented on src/chocobot/curseforge/Curseforge.py
> +     def update_cf(self) -> None:
My goal was to have less requests overall so that were didnt hit our API limit (we'd run the update method whenever a new version was out) - I assume it isnt worth it?

Ill just change it to sets/gets

2024-09-17 01:59 UTC, Jonah-Hansen approved these changes

2024-09-17 01:59 UTC, merged